variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

check:
  stage: test
  script: gradlew check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

  artifacts:
    expose_as: "Checkstyle Results"
    paths: ['build/reports/checkstyle/main.html']



test:
  stage: test
  script: gradlew test

  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml